---
- name: Ejecutar script SQL usando SQL*Plus
  shell: " $ORACLE_HOME/bin/sqlplus -S {{ oracle_user }}/{{ oracle_password }}@localhost:{{ oracle_port }}/{{ oracle_database }} <<EOF
        SET PAGESIZE 0
        SET FEEDBACK OFF
        SET HEADING OFF
        SET ECHO OFF
        SET MARKUP HTML OFF
        SET COLSEP ","
        SPOOL /home/oracle/temp_file.sql
        SELECT contenido FROM scripts WHERE nombre = 'script_ejemplo2.sql';
        SPOOL OFF
        EXIT
    EOF"
  environment: 
    ORACLE_HOME: "{{ variable_home }}"
    LD_LIBRARY_PATH: "{{ ld_path }}"
    PATH: "{{ path_bin }}"
  register: sqlplus_output
  
- name: Mostrar salida de SQL*Plus
  debug:
    var: sqlplus_output.stdout_lines